Repository findologic/libflexport, pull requests merged in 2018-06, with the labels that each got.

#42 CSV support
  src/FINDOLOGIC/Export/CSV/CSVExporter.php
  src/FINDOLOGIC/Export/CSV/CSVItem.php
  src/FINDOLOGIC/Export/Data/AllKeywords.php
  src/FINDOLOGIC/Export/Data/AllOrdernumbers.php
  src/FINDOLOGIC/Export/Data/Attribute.php
  src/FINDOLOGIC/Export/Data/DateAdded.php
  src/FINDOLOGIC/Export/Data/Image.php
  src/FINDOLOGIC/Export/Data/Item.php
  src/FINDOLOGIC/Export/Data/Usergroup.php
  src/FINDOLOGIC/Export/Exporter.php
  src/FINDOLOGIC/Export/Helpers/DataHelper.php
  src/FINDOLOGIC/Export/Helpers/Serializable.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareMultiValue.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareMultiValueItem.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareSimpleValue.php
  src/FINDOLOGIC/Export/XML/XMLItem.php
  tests/FINDOLOGIC/Export/Tests/CSVSerializationTest.php
Labels: enhancement

#46 Check if input of url and image elements are urls
  src/FINDOLOGIC/Export/Data/Image.php
  src/FINDOLOGIC/Export/Data/Url.php
  src/FINDOLOGIC/Export/Helpers/DataHelper.php
  tests/FINDOLOGIC/Export/Tests/CSVSerializationTest.php
  tests/FINDOLOGIC/Export/Tests/DataElementsTest.php
  tests/FINDOLOGIC/Export/Tests/XmlSerializationTest.php
Labels: bug

#55 Improve code coverage and fix bug
  .codeclimate.yml
  src/FINDOLOGIC/Export/Data/Image.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareMultiValue.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareMultiValueItem.php
  src/FINDOLOGIC/Export/Helpers/UsergroupAwareSimpleValue.php
  tests/FINDOLOGIC/Export/Tests/XmlSerializationTest.php
Labels: bug, enhancement

#57 Mention encoding limitations
  README.md
Labels: enhancement
